### ISSUE TITLE
Infinite Scroll should be configurable. A publisher may choose to enabled or disable infinite scroll. 

### ISSUE THREAD

**Issue by prvthi** [quintype/malibu#6]

**Comment by YAMINIPRIYA16** [comment]
Test scenarios covered.
1.Verify whether the page does not break when a collection is put into the collection containing slug called **curated-story-list** 
2.Verify whether the infinite scroll shows the stories on the right side of the sorter.
3.Verify whether the infinite scroll doesn't break when there are no stories put in the right side in a manual collection.
4.Verify whether the order of display of the stories are as per the sorted order from the right side followed by the stories on the left side.
